name: bdverse-master-branch-CI

# Controls when the action will run. Triggers the workflow on push or pull request
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    # Runs a single command using the runners shell
    - name: Run a one-line script
      run: echo Hello, world!
# below lines will run after R-CMD-check is OK
# this sends trigger to repos mentioned below.
# workflow to be triggered has to be in master branch.
# currently REPO_ACCESS_TOKEN is in organization secret with only public repo access.
  dispatch:
    needs: build
    strategy:
      matrix:
        repo: ['bd-R/bdutilities', 'bd-R/bdDwC', 'bd-R/bdchecks']
    runs-on: ubuntu-latest
    steps:
      - name: Repository Dispatch
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.REPO_ACCESS_TOKEN }}
          repository: ${{ matrix.repo }}
          event-type: my-event
