name: Triggering binder

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Fetch URL
      uses: boyeborg/fetch-url-action@v1.1
      with:
        # The url to fetch
        url: https://mybinder.org/v2/gh/bd-R/bdverse/master?urlpath=rstudio
